### ISSUE TITLE
Loading of chunks still doesn't work

### ISSUE THREAD

**Issue by phiros** [vigneshshanmugam/tailor-spa#4]
When I click on any category (either SHOP FOR MEN or SHOP FOR WOMAN) I get the following errors in chromes console:

```
bundle.js:140 Error: Loading chunk 0 failed.(…)__webpack_require__.oe @ bundle.js:140
bundle.js:94 Uncaught (in promise) Error: Loading chunk 0 failed.(…)onScriptComplete @ bundle.js:94
```

**Comment by vigneshshanmugam** [comment]
my bad..addressed it..https://github.com/vigneshshanmugam/tailor-spa/commit/080e3d560601a3a1f8a5cbcf9489d82653cc8d67

Please try out now.. Thanks!
